***
## Loading and saving
Getting data into and out of our program is vitally important. In this workshop we will look at some fundamentals of loading and saving data.  Once we have done that we will look at specific code to handle the data we are most likely to use.

***
### Loading a text file.

In [1]:
f = open("Data/demofile.txt", "r")
print(f.read())
f.close()

Far out in the uncharted backwaters of the unfashionable end of the western spiral arm of the Galaxy lies a small unregarded yellow sun.
Orbiting this at a distance of roughly ninetytwo million miles is an utterly insignificant little blue green planet whose ape descended life forms are so amazingly primitive that they still think digital watches are a pretty neat idea.


In [3]:
f = open("Data/demofile.txt", "r")
print(f.readline())
f.close()

Far out in the uncharted backwaters of the unfashionable end of the western spiral arm of the Galaxy lies a small unregarded yellow sun.



***
##### These are the codes you can use to define how you want to open the file
"r" - Read - Default value. Opens a file for reading, error if the file does not exist

"a" - Append - Opens a file for appending, creates the file if it does not exist

"w" - Write - Opens a file for writing, creates the file if it does not exist

"x" - Create - Creates the specified file, returns an error if the file exists

In [2]:
f = open("Data/demofile.txt", "r")
for x in f:
    print(x) # This reads a line at a time
f.close()

Far out in the uncharted backwaters of the unfashionable end of the western spiral arm of the Galaxy lies a small unregarded yellow sun.


Orbiting this at a distance of roughly ninetytwo million miles is an utterly insignificant little blue green planet whose ape descended life forms are so amazingly primitive that they still think digital watches are a pretty neat idea.



Remember that x above is a string of characters

In [6]:
f = open("Data/demofile.txt", "r")
for x in f:
    for y in x:
        print(y)
f.close()

F
a
r
 
o
u
t
 
i
n
 
t
h
e
 
u
n
c
h
a
r
t
e
d
 
b
a
c
k
w
a
t
e
r
s
 
o
f
 
t
h
e
 
u
n
f
a
s
h
i
o
n
a
b
l
e
 
e
n
d
 
o
f
 
t
h
e
 
w
e
s
t
e
r
n
 
s
p
i
r
a
l
 
a
r
m
 
o
f
 
t
h
e
 
G
a
l
a
x
y
 
l
i
e
s
 
a
 
s
m
a
l
l
 
u
n
r
e
g
a
r
d
e
d
 
y
e
l
l
o
w
 
s
u
n
.


O
r
b
i
t
i
n
g
 
t
h
i
s
 
a
t
 
a
 
d
i
s
t
a
n
c
e
 
o
f
 
r
o
u
g
h
l
y
 
n
i
n
e
t
y
t
w
o
 
m
i
l
l
i
o
n
 
m
i
l
e
s
 
i
s
 
a
n
 
u
t
t
e
r
l
y
 
i
n
s
i
g
n
i
f
i
c
a
n
t
 
l
i
t
t
l
e
 
b
l
u
e
 
g
r
e
e
n
 
p
l
a
n
e
t
 
w
h
o
s
e
 
a
p
e
 
d
e
s
c
e
n
d
e
d
 
l
i
f
e
 
f
o
r
m
s
 
a
r
e
 
s
o
 
a
m
a
z
i
n
g
l
y
 
p
r
i
m
i
t
i
v
e
 
t
h
a
t
 
t
h
e
y
 
s
t
i
l
l
 
t
h
i
n
k
 
d
i
g
i
t
a
l
 
w
a
t
c
h
e
s
 
a
r
e
 
a
 
p
r
e
t
t
y
 
n
e
a
t
 
i
d
e
a
.


In [3]:
f = open("Data/demofile.txt", "r")
print(f.read(5)) # Read in 5 characters
# note f.read() reads all the characters.
f.close()

Far o


We can use the ascii code to look for specific

In [7]:
f = open("Data/demofile.txt", "r")
for x in f:
    for y in x:
        if y == '\n': # This looks for a new line character, if one is found it prints an new line.
            print()
        elif y =='a': # If the character is an A it prints it in uppercase
            print(y.upper(), end='')
        else:# Else it just prints the charcater.
            print(y.lower(), end='')
f.close()

fAr out in the unchArted bAckwAters of the unfAshionAble end of the western spirAl Arm of the gAlAxy lies A smAll unregArded yellow sun.
orbiting this At A distAnce of roughly ninetytwo million miles is An utterly insignificAnt little blue green plAnet whose Ape descended life forms Are so AmAzingly primitive thAt they still think digitAl wAtches Are A pretty neAt ideA.

***
### Writing to a file to a file
To write a file, we first open the file, we leave the file open while we write to it, the with open line will close the file when it as finished

In [4]:
# This writes the text read me to a file
with open('Data/readme.txt', 'w') as f:
    f.write('readme')
f.close()

***
### Writing comma separated value (CSV) files.
CSV files are a very common method of saving numerical data. They generally have a header which text seperated via commas ','.  Each header defines a column, numerical data is stored in the same way as the header (stored as text) again separated with commas.
|  Time | Value  |
|  0      | 0.01      |
|  1      | 0.03      |
|  2      | 0.04      |
|  3      | 0.07      |

Let us build a file which saves some data

In [30]:
# We will build a 2D array the first axis will hold an angle and the second will hold the cos value for the angle
import numpy as np
myData = np.zeros([10,2])
myData[:,0] = np.linspace(0, 6.28, 10)
myData[:,1] = np.cos(myData[:,0])

#Let's build our header
ourHeader = 'Angle' + ',' + 'Cos Value' + "\n"
# Now lets open our file
with open('ourData.txt', 'w') as f:
    #Write the header
    f.write(ourHeader)
    for row in myData:
        f.write(str(row[0]))
        f.write(',')
        f.write(str(row[1]))
        f.write('\n') # I don't need a second '

# Although this code might seem compliacted it is actually quite simple once you read through it.  Once written you should be able to load the file in a spreadsheet such as excel or google sheets

***
### Is there an easier way
Yes, there is. As we mentioned earlier numpy is designed to help us deal with numbers. We also said that most data we want to deal with is stored as a csv file.  So it makes sense that numpy knows about csv files and can read them.

##### Loading

In [31]:
# We will use the file we just created as an exmple file to load
import numpy as np
fileName = 'Data/ourData.txt'
myLoadedData = np.genfromtxt(fileName,delimiter=',',skip_header=1)
# filename is the file we want to load
# delimiter = ',' tells python what seperates the data within the file, in this case a comma
# skip_header = 1
print(myLoadedData)

[[ 0.          1.        ]
 [ 0.69777778  0.76627189]
 [ 1.39555556  0.17434523]
 [ 2.09333333 -0.4990802 ]
 [ 2.79111111 -0.93920748]
 [ 3.48888889 -0.94029639]
 [ 4.18666667 -0.50183791]
 [ 4.88444444  0.17120782]
 [ 5.58222222  0.7642214 ]
 [ 6.28        0.99999493]]


##### Saving
Saving is very similar in numpy using the savetxt function. Three arguments are needed, the filename to save to, the array to save and the delimiter to use in our case a comma.

In [ ]:
# Example of saving
fileName = "resavedData.csv"
np.savetxt(fileName, myLoadedData, delimiter=",")

***
#### One last thing
If you want to store data to move it between python programs, or if you are not inteding on loading it in a differnt program you may want to save the numpy array as a numpy array using the np.save command, the np.load command will return the array.

In [35]:
# here is an example of loading and saving a numy array
testArray = np.random.random([3,3])
print(testArray)
print()
np.save('testsave', testArray)
loadedTestArray = np.load("testsave.npy")
print(loadedTestArray)

[[0.38060826 0.46329925 0.01969185]
 [0.39944776 0.17051674 0.78433374]
 [0.63557868 0.68812403 0.89434825]]

[[0.38060826 0.46329925 0.01969185]
 [0.39944776 0.17051674 0.78433374]
 [0.63557868 0.68812403 0.89434825]]
