***
### Problem 1
Write a function to return the sum, difference, product and the ratio of two given numbers.
The function should take two numbers as arguments and return four.  These four numbers should then be printed.
***

In [1]:
# Enter your code here
def my_function(number1, number2):
    sum = number1 + number2
    difference = number1 - number2
    product = number1 * number2
    ratio = number1 / number2
    return sum, difference, product, ratio

# Test
print(my_function(2,3))

(5, -1, 6, 0.6666666666666666)


***

***
### Problem 2
Write a function to convert radians to degrees, the input should be in radians and the function should return degrees.

In [3]:
# Enter your code here
def convert_angle(radians):
    return (radians * 360 /(2*3.14159))

# Test
print(convert_angle(1))

57.295827908797776


***
### Problem 3
Write a function to calculate the speed a falling object reaches after a given time, you can assume the acceleration due to gravity is 9.8 $m^{-2}$.  The velocity of an object under constant acceleration is given by $v^2 = 2at^2$. Test your code.

In [5]:
# Enter your code here
def calculate_speed(time):
    return (2 * 9.8 * time**2)**0.5

#Test
print(calculate_speed(2))

8.854377448471462


***
### Problem 4
Write a function to calculate the kinetic energy of an object from its mass and velocity.

In [7]:
# Enter your code here
def calculate_KE(mass, velocity):
    return mass * velocity**2

***
### Problem 5
Use the two previously created programs to calculate the kinetic energy of a skydiver after 10 seconds. You can assume the weight of the skydiver is 80 Kg

In [9]:
# Enter your code here
time = 10
mass = 80
print('The KE is', calculate_KE(mass, calculate_speed(time)), 'J')

The KE is 156800.00000000003 J


***
### Problem 6
Write a function to add together two numbers and divide the result by a third number.  The three numbers should be supplied as arguments and the last number, the one used for division, should be optional with a default value of 1.

In [13]:
def mathFunction(fisrt, second, third=1):
    return (fisrt + second) / third

print(mathFunction(2,2,2))
print(mathFunction(2,2))

2.0
4.0


***
### Problem 7
Write a function to normalise a given array, the sum of the array should equal 1.
To help you have been given an array

In [12]:
import numpy as np
array = np.asarray([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20],
                    [21, 22, 23, 24, 25]])

def normalise(array):
    sumOfArray = array.sum() # This is tricky
    return array/sumOfArray

#Test
print(normalise(array))

325
[[0.00307692 0.00615385 0.00923077 0.01230769 0.01538462]
 [0.01846154 0.02153846 0.02461538 0.02769231 0.03076923]
 [0.03384615 0.03692308 0.04       0.04307692 0.04615385]
 [0.04923077 0.05230769 0.05538462 0.05846154 0.06153846]
 [0.06461538 0.06769231 0.07076923 0.07384615 0.07692308]]


***
### Problem 8
This is a quite complicated piece of code can you work out what it does. Can you change the code to help you work out what is going on?
There is no real problem here more of a test yourself.

In [12]:
import numpy as np
# This defines oue test number, what are we testing for?
testnumber = 73

testnumbers = np.ones(testnumber-3) * testnumber
# What is testnumbers?
print(testnumbers)

numbers = np.linspace(3, testnumber-1, testnumber-3)
#what are these numbers?
print(numbers)

#Why does numbers start at 3?
# because 1 would always return the number as prime, because all numbers are divisible by 1

outcomes = testnumbers % numbers
# What is this line doing?
print(outcomes) # what does outcomes look like

print(testnumber, 'is not a prime =', 0 in outcomes)
# Why would a 0 indicate a prime?

73 is not a prime =  False
