***
# Problems for week 2
In this workshop you will be presented with a number of challenges to help you practice data structures in python. If you have any problems raise your hand.

***
### Slicing: Problem 1
We will use a predefined list in the fisrt part to explore using the slicing commands.

In [1]:
myData = ['Algiers', 'Bridgetown', 'Copenhagen', 'Dakar', 'Funafuti', 'Georgetown', 'Helsinki', 'Jakarta', 'Kinshasa', 'Lisbon', 'Monrovia']

Using the cell below print the 5th entry in the list called myData

In [3]:
print(myData[4])

Funafuti


Print the 3rd to the 7th (inclusive) items

In [4]:
print(myData[3:8])

['Dakar', 'Funafuti', 'Georgetown', 'Helsinki', 'Jakarta']


Print the last 3 items

In [2]:
print(myData[-3:])

['Kinshasa', 'Lisbon', 'Monrovia']


***
### Tuple methods: Problem 2
Now we will get some practice at using methods.
Copy the data and using methods reverse the list, then print it.

In [3]:
newList = myData
newList.reverse()
print(newList)


['Monrovia', 'Lisbon', 'Kinshasa', 'Jakarta', 'Helsinki', 'Georgetown', 'Funafuti', 'Dakar', 'Copenhagen', 'Bridgetown', 'Algiers']


use the pop() method and len() function to remove the last item from the original data

In [8]:
print(myData)
myData.pop(len(myData)-1)
print(myData)

['Algiers', 'Bridgetown', 'Copenhagen', 'Dakar', 'Funafuti', 'Georgetown', 'Helsinki', 'Jakarta', 'Kinshasa', 'Lisbon', 'Monrovia']
['Algiers', 'Bridgetown', 'Copenhagen', 'Dakar', 'Funafuti', 'Georgetown', 'Helsinki', 'Jakarta', 'Kinshasa', 'Lisbon']


***
### Dictionaries: Problem 3
Create a dictionary to store details about a person, such as age, height, course title, grade... It is up to you what to put in.

In [10]:
personOne = {"name": "Buzz", "LastName": "Lightyear", "Grade": 100}

Make a second dictionary for a second individual.
Now make a list with the first item the first dictionary and the second the second dictionary.
Print out one item from the list.

In [12]:
personTwo = {"name": "Woody", "LastName": "Pride", "Grade": 90}

people =[personOne, personTwo]

print(people[1]["name"])

Buzz


***
## Numpy
The remaining problems concern using numpy

##### Reshaping
Make a 1D array 25 items in length with each item being the value 1.
Then reshape the array in to a 5 by 5 array and print the array.

In [13]:
# Put your code here
import numpy as np
myArray = np.ones(25)
myArray = np.reshape(myArray,[5,5])
print(myArray)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


##### Some maths
Generate a 1D array 10 numbers in length filled with values between 0 and 6.28
Use this array to generate the corresponding sin values.

In [ ]:
# Put your code here
x = np.linspace(0, 6.28, 10)
y = np.sin(x)

***
### Problem
Work through the code below and see if you can work out what it is doing.  This is quite a powerful use of numpy, talk it over with your classmates. Note the % operators returns the remainder of division.

In [21]:
import numpy as np
# This defines oue test number, what are we testing for?
testnumber = 23

testnumbers = np.ones(testnumber-3) * testnumber
# What is testnumbers? This is a 1D array filled with the test number, it has a size equal to test number -3
# print(testnumbers)

numbers = np.linspace(2, testnumber-1, testnumber-3)
#what are these numbers? This is an array of numbers from 3 up to 1 below the test number
#print(numbers)

#Why does numbers start at 2? We are not interested in 1( all numbers are divisible by 1).

outcomes = testnumbers % numbers
# What is this line doing? This produces an array filled with the reminder after division for every number in the two arrays
#print(outcomes) # what does outcomes look like

print(testnumber, 'is a prime =', not(0 in outcomes))
# Why would a 0 indicate a prime?
# Does 0 exist in the data, if it does then the reminder after division returned a 0 which means it found an exact divider (ie. not a prime), in returns a true or false
# I use the not command to turn a true in to a false and a false in to a true.

23 is a prime = True
