## How to solve any coding problem in 5 steps

In this notebook we will look at the easiest way to solve any problem.
* 1 Google
* 2 Stack Overflow
* 3 Implementation
* 4 Documentation
* 5 Customise

***
### Our problem
I want to replace all the zeros in a numpy array with 1s
***

# 1 Google
Type your problem in to google, I want to replace all the zeros in a numpy array with ones.

<p align="left">
<img src="Images/One.png" alt="drawing" width="1200"/>
</p>

## Stack overflow
Stack overflow is an online community of coders of all capabilities who give each other advice.  It is how most people code now days.
This is the answer I got

<p align="left">
<img src="Images/2.png" alt="drawing" width="1200"/>
</p>

The code I am given as an example is arr[arr > 255] = x
The explanation tells me that this will take and array called arr and return the same array but anything with a value over 255 will be replaced by the value x.  Let's try it.

### Implementation

In [7]:
import numpy as np
# Here I generate a text array
myArray = np.asarray([[1,2,3,256],
                     [1,2,256,4],
                     [1,256,3,4],
                     [256,2,3,4]])

print(myArray)

# Then I use the code above
myArray[myArray > 255] = 1
print()
print(myArray)

# it seems to work

[[  1   2   3 256]
 [  1   2 256   4]
 [  1 256   3   4]
 [256   2   3   4]]

[[1 2 3 1]
 [1 2 1 4]
 [1 1 3 4]
 [1 2 3 4]]


## Documentations
The example mentions indexing numpy arrays
from numpy.org

https://numpy.org/doc/stable/user/how-to-index.html?highlight=index


## Adapting / customise
We don't want to change items with values over 255 we want items with values equal to 0.
So we can change the conditional statement form > (greater than) to == (equals)



In [9]:
myArray = np.asarray([[1,2,3,0],
                      [1,2,0,4],
                      [1,0,3,4],
                      [0,2,3,4]])
myArray[myArray ==0 ] = 1

print(myArray)

[[1 2 3 1]
 [1 2 1 4]
 [1 1 3 4]
 [1 2 3 4]]
